receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch: {}

exporters:
  prometheus:
    endpoint: "0.0.0.0:9464"

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
# You can uncomment and configure the following sections to enable traces and logs collection      
#    traces:
#      receivers: [otlp]
#      processors: [batch]
#      exporters: []   # tu pourras ajouter Tempo ou Grafana Cloud plus tard
#    logs:
#      receivers: [otlp]
#      processors: [batch]
#      exporters: []   # idem pour Loki / Grafana Cloud